### ISSUE TITLE
Should Even be owned by an organization?

### ISSUE THREAD

**Issue by DamianReeves** [evendotnet/Even#18]
I think in order to have the proper rights to setup AppVeyor and/or MyGet builds that the best option is to have Even as a github organization i.e. EvenDotNet. With an organization we can actually form a first class team around the project. 
Does this make sense?

**Comment by nvivo** [comment]
That's probably the right way to do it. I'll create one.

**Comment by promontis** [comment]
+1 for this

**Comment by promontis** [comment]
We should also create a Gitter and also a readme.io since I reckon we'll eventually have a lot of docs

**Comment by nvivo** [comment]
There you go: https://gitter.im/evendotnet/Even

**Comment by DamianReeves** [comment]
Nice
