### ISSUE TITLE
Create an automated build script.

### ISSUE THREAD

**Issue by DamianReeves** [evendotnet/Even#5]
This project is in need of a build script to be used in build automation.
Should this script use FAKE, Cake, or some other toolset?

**Comment by rodrigovidal** [comment]
I could help setting up a fake script, what do you think @nvivo ?

**Comment by nvivo** [comment]
I think this is a good idea @DamianReeves. 

@rodrigovidal,  if you can help us with this it would be great!

**Comment by DamianReeves** [comment]
I've started working on this.

**Comment by promontis** [comment]
We also need a good nuget package. The current one doesn't seem to work with DNX 4.5.1. Akka does work with it, so perhaps we should use the Akka nuspec file as a base file?

**Comment by promontis** [comment]
@nvivo What about using myget as a CI for this project? Tried it myself, and all works if I disable the test project. Don't need to specify any nuspec and such. It does this all for you it seems. We should fix the tests though

**Comment by nvivo** [comment]
@promontis I think it's a good idea to have some form of CI, but I never setup myget. Are you familiar with this? What would it take?

**Comment by DamianReeves** [comment]
I was thinking AppVeyor would be a good build platform, but if we want a nuget feed for nightly builds or CI builds then myget makes sense as the feed host, I'm not sure about it being the build platform though.
I'm going to get back to this, I'm just shaking the dust off following my holiday break.

**Comment by nvivo** [comment]
I need to check the options too. I just created issue #17 to discuss this.

**Comment by DamianReeves** [comment]
This has been created. So closing.
